# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '9.3'

target 'Ortalama' do
  # Comment the next line if you don't want to use dynamic frameworks
  

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'RNRate', :path => '../node_modules/react-native-rate/ios'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end
